global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets:
        - "rabbitmq:15692"
  - job_name: "rabbitmq-detailed"
    metrics_path: "/metrics/detailed"
    params:
      family: ["queue_coarse_metrics"]
    static_configs:
      - targets:
        - "rabbitmq:15692"
