{
 "title": "Metrics",
 "description": "sccache-dist scheduler metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "arch", "label": "CPU Architecture", "query": "x86_64,aarch64" },
   {
    "name": "scheduler_id",
    "label": "Scheduler",
    "query": {
     "query": "label_values(sccache::scheduler::cpu_usage_ratio{env=~\"linux-${arch}\"},scheduler_id)"
    }
   },
   {
    "name": "server_id",
    "label": "Server",
    "query": {
     "query": "label_values(sccache::server::cpu_usage_ratio{env=~\"linux-${arch}\"},server_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sccache::server::job_pending_count{env=~\"linux-${arch}\", server_id=~\"$server_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sccache::scheduler::http::request_time_count{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", path=\"/api/v2/jobs/new\", method=\"POST\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(scheduler_id) (present_over_time(sccache::scheduler::cpu_usage_ratio{env=~\"linux-${arch}\"}[15s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(server_id) (present_over_time(sccache::server::cpu_usage_ratio{env=~\"linux-${arch}\"}[15s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Jobs per user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(username) (sccache::scheduler::http::request_time_count{authorized=\"true\", env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", path=\"/api/v2/jobs/new\", method=\"POST\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Jobs per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(username) (sccache::scheduler::http::request_time_count{authorized=\"true\", env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", path=\"/api/v2/jobs/new\", method=\"POST\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Job Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max (sccache::server::run_job_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "total (max)"
    },
    {
     "expr": "max (sccache::server::run_build_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "build (max)"
    },
    {
     "expr": "max (sccache::server::load_job_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "load (max)"
    },
    {
     "expr": "avg (sccache::server::run_job_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "total (avg)"
    },
    {
     "expr": "avg (sccache::server::run_build_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "build (avg)"
    },
    {
     "expr": "avg (sccache::server::load_job_time{env=~\"linux-${arch}\", server_id=~\"${server_id}\"})",
     "legendFormat": "load (avg)"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU counts vs. utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (env) (avg by(env, server_id) (avg_over_time(sccache::server::num_cpus{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval])))",
     "legendFormat": "# {{env}}"
    },
    {
     "expr": "avg by(env) (avg_over_time(sccache::server::cpu_usage_ratio{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]))",
     "legendFormat": "% {{env}}"
    },
    {
     "expr": "avg by(server_id) (avg_over_time(sccache::server::cpu_usage_ratio{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]))",
     "legendFormat": "% {{server_id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(env) (avg_over_time(sccache::server::mem_used_bytes{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]) / avg_over_time(sccache::server::mem_total_bytes{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]) * 100)",
     "legendFormat": "% {{env}}"
    },
    {
     "expr": "avg by(server_id) (avg_over_time(sccache::server::mem_used_bytes{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]) / avg_over_time(sccache::server::mem_total_bytes{env=~\"linux-${arch}\", server_id=~\"${server_id}\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, method) (rate(sccache::scheduler::http::request_count{authorized=\"true\", env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by(path, method) (rate(sccache::scheduler::http::request_count{authorized=\"false\", env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", method=\"GET\", path=\"/api/v2/status\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}} (healthcheck)"
    },
    {
     "expr": "sum by(path, method) (rate(sccache::scheduler::http::request_count{authorized=\"false\", env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", method!=\"GET\", path!=\"/api/v2/status\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}} (unauthorized)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (path, method) (sccache::scheduler::http::request_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", path!=\"/api/v2/job/:job_id\"})",
     "legendFormat": "HTTP {{method}} {{path}}"
    },
    {
     "expr": "avg (sccache::scheduler::http::request_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\", path!=\"/api/v2/job/:job_id\"})",
     "legendFormat": "HTTP (avg)"
    },
    {
     "expr": "avg (sccache::scheduler::has_job_inputs_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Has job inputs"
    },
    {
     "expr": "avg (sccache::scheduler::has_job_result_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Has job result"
    },
    {
     "expr": "avg (sccache::scheduler::get_job_result_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Get job result"
    },
    {
     "expr": "avg (sccache::scheduler::del_job_inputs_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Del job inputs"
    },
    {
     "expr": "avg (sccache::scheduler::del_job_result_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Del job result"
    },
    {
     "expr": "avg (sccache::scheduler::put_job_inputs_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Put job inputs"
    },
    {
     "expr": "avg (sccache::scheduler::put_toolchain_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Put toolchain"
    },
    {
     "expr": "avg (sccache::scheduler::del_toolchain_time{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"})",
     "legendFormat": "Del toolchain"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(env) (avg_over_time(sccache::scheduler::cpu_usage_ratio{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]))",
     "legendFormat": "% {{env}}"
    },
    {
     "expr": "avg by(scheduler_id) (avg_over_time(sccache::scheduler::cpu_usage_ratio{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]))",
     "legendFormat": "{{scheduler_id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(env) (avg_over_time(sccache::scheduler::mem_used_bytes{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]) / avg_over_time(sccache::scheduler::mem_total_bytes{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]) * 100)",
     "legendFormat": "% {{env}}"
    },
    {
     "expr": "avg by(scheduler_id) (avg_over_time(sccache::scheduler::mem_used_bytes{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]) / avg_over_time(sccache::scheduler::mem_total_bytes{env=~\"linux-${arch}\", scheduler_id=~\"${scheduler_id}\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{scheduler_id}}"
    }
   ]
  }
 ]
}