{
 "title": "AMD64",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Compilations",
   "type": "stat",
   "description": "Total number of compilations performed by the build cluster",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(sccache::server::job_finished_count{env=\"linux-amd64\"}[$__range]))",
     "legendFormat": "jobs finished"
    }
   ]
  },
  {
   "title": "Active Compilations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sccache::server::job_pending_count{env=\"linux-amd64\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(env) (count by(env, scheduler_id) (present_over_time(sccache::scheduler::http::request_count{env=\"linux-amd64\"}[3m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(env) (count by(env, server_id) (present_over_time(sccache::server::cpu_usage_ratio{env=\"linux-amd64\"}[$__rate_interval])))",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(env) (sccache::server::cpu_usage_ratio{env=\"linux-amd64\"})",
     "legendFormat": "ASG avg"
    },
    {
     "expr": "avg by(server_id) (sccache::server::cpu_usage_ratio{env=\"linux-amd64\"})",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(env) (sccache::server::mem_used_bytes{env=\"linux-amd64\"} / sccache::server::mem_total_bytes{env=\"linux-amd64\"} * 100)",
     "legendFormat": "ASG avg"
    },
    {
     "expr": "avg by(server_id) (sccache::server::mem_used_bytes{env=\"linux-amd64\"} / sccache::server::mem_total_bytes{env=\"linux-amd64\"} * 100)",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Job Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(sccache::server::load_job_time{env=\"linux-amd64\"})",
     "legendFormat": "load job"
    },
    {
     "expr": "max(sccache::server::run_build_time{env=\"linux-amd64\"})",
     "legendFormat": "run build (max)"
    },
    {
     "expr": "avg(sccache::server::run_build_time{env=\"linux-amd64\"})",
     "legendFormat": "run build (avg)"
    },
    {
     "expr": "avg(sccache::server::run_job_time{env=\"linux-amd64\"})",
     "legendFormat": "job total (avg)"
    },
    {
     "expr": "max(sccache::server::run_job_time{env=\"linux-amd64\"})",
     "legendFormat": "job total (max)"
    },
    {
     "expr": "max(sccache::server::toolchain::load_time{env=\"linux-amd64\"})",
     "legendFormat": "load toolchain (avg)"
    },
    {
     "expr": "max(sccache::server::toolchain::load_time{env=\"linux-amd64\"})",
     "legendFormat": "load toolchain (max)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Scheduler HTTP and Server job throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(sccache::server::job_accepted_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "jobs accepted"
    },
    {
     "expr": "sum(rate(sccache::server::job_loaded_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "jobs loaded"
    },
    {
     "expr": "sum(rate(sccache::server::job_finished_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "jobs finished"
    },
    {
     "expr": "sum by(path, method) (rate(sccache::scheduler::http::request_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Scheduler I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (sccache::scheduler::has_job_inputs_time{env=\"linux-amd64\"})",
     "legendFormat": "has inputs"
    },
    {
     "expr": "avg (sccache::scheduler::has_job_result_time{env=\"linux-amd64\"})",
     "legendFormat": "has result"
    },
    {
     "expr": "avg (sccache::scheduler::get_job_result_time{env=\"linux-amd64\"})",
     "legendFormat": "get result"
    },
    {
     "expr": "avg (sccache::scheduler::del_job_result_time{env=\"linux-amd64\"})",
     "legendFormat": "del result"
    },
    {
     "expr": "avg (sccache::scheduler::put_job_inputs_time{env=\"linux-amd64\"})",
     "legendFormat": "put inputs"
    },
    {
     "expr": "avg (sccache::scheduler::put_toolchain_time{env=\"linux-amd64\"})",
     "legendFormat": "put toolchain"
    }
   ]
  },
  {
   "title": "Server I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(sccache::server::get_toolchain_time{env=\"linux-amd64\"})",
     "legendFormat": "get toolchain"
    },
    {
     "expr": "avg(sccache::server::toolchain::unpack_inflated_time{env=\"linux-amd64\"})",
     "legendFormat": "unpack toolchain"
    },
    {
     "expr": "avg(sccache::server::get_job_inputs_time{env=\"linux-amd64\"})",
     "legendFormat": "get inputs"
    },
    {
     "expr": "avg(sccache::server::put_job_result_time{env=\"linux-amd64\"})",
     "legendFormat": "put result"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(sccache::scheduler::put_job_inputs_error_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "put inputs"
    },
    {
     "expr": "sum(rate(sccache::server::toolchain_error_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "load toolchain"
    },
    {
     "expr": "sum(rate(sccache::server::get_job_inputs_error_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "get inputs"
    },
    {
     "expr": "sum(rate(sccache::server::job_build_error_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "run build"
    },
    {
     "expr": "sum(rate(sccache::server::put_job_result_error_count{env=\"linux-amd64\"}[$__rate_interval]))",
     "legendFormat": "put result"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(username) (sccache::scheduler::http::request_count{env=\"linux-amd64\", method=\"POST\"})",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}