FROM ubuntu:latest

RUN apt update \
 && DEBIAN_FRONTEND=noninteractive \
    apt install -y --no-install-recommends libcap2 bubblewrap \
 && apt clean \
 && rm -rf /tmp/* /var/tmp/* /var/cache/apt/* /var/lib/apt/lists/*
