name: free-disk-space

description: Free up disk space on the GitHub-hosted runners

inputs:
  tool_cache:
    type: string
    required: true
    description: Runner tool_cache

runs:
  using: composite
  steps:
    - name: Free up disk space
      shell: bash --noprofile --norc -eo pipefail {0}
      env:
        TIMEFORMAT: 'time: %3lR'
      run: |
        _run_cmd() {
          time sudo -s /bin/bash -cx "$@"
          df -h --output='size,avail,used,pcent' /
        }
        _run_cmd 'echo "initial size:"'
        # _run_cmd 'docker images; docker rmi $(docker image ls -aq) || true; docker images'
        _run_cmd 'swapoff -a && rm -f /swapfile /mnt/swapfile && apt clean'
        # _run_cmd 'rm -rf /opt/{az,ghc,google,microsoft}'
        _run_cmd 'rm -rf /usr/lib/mono'
        _run_cmd 'rm -rf /usr/local/julia*'
        _run_cmd 'rm -rf /usr/local/.ghcup'
        _run_cmd 'rm -rf /usr/share/az_*'
        _run_cmd 'rm -rf /usr/share/gradle-*'
        # _run_cmd 'rm -rf /usr/share/{swift,dotnet,kotlinc,miniconda}'
        # _run_cmd 'rm -rf /usr/local/lib/android'
        _run_cmd 'rm -rf /usr/local/share/{boost,chromium,powershell}'
        _run_cmd 'rm -rf /home/linuxbrew/.linuxbrew'
        # _run_cmd 'rm -rf "${{ inputs.tool_cache }}"/{go,Ruby,PyPy,CodeQL,Python}'
